name: Code Format Check

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  code-format-check:
    name: Code Format Check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Install golangci-lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin latest
        golangci-lint --version

    - name: Check code format
      run: |
        golangci-lint run --disable-all --enable=goimports,gofmt --timeout=5m --color=always
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Comment on PR
      uses: actions/github-script@v4
      if: always()
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: | 
          if ((github.event_name == 'pull_request'|| github.event_name == 'push')&& steps.code-format-check.outcome == 'failure') {
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Hey @' + context.payload.pull_request.user.login + ', Your code formatting needs some work, please update the code formatting accordingly 🙏'
            })
          }
